# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 18:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20180218_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='outside_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 27, 18, 32, 11, 480223)),
            preserve_default=False,
        ),
    ]
