# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-12 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20180227_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='stand',
            field=models.BooleanField(default=False),
        ),
    ]
