# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import locations.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_stand'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=locations.models.upload_image_path),
        ),
    ]
