# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-13 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180213_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stand',
        ),
    ]
