# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-13 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180213_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ManyToManyField(help_text='Select Location(s)', to='products.Genre'),
        ),
    ]
