# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-13 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180213_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('breed', models.CharField(choices=[('firstsa', 'first breed'), ('second32', 'second breed')], max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('first', 'first gener'), ('second', 'second gener')], max_length=6)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='manufacturer',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.AddField(
            model_name='dog',
            name='owners',
            field=models.ManyToManyField(to='products.Owner'),
        ),
    ]
