# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-13 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180213_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ManyToManyField(to='products.Location'),
        ),
    ]
