# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-17 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180214_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=datetime.datetime(2018, 2, 17, 20, 37, 52, 678838, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
    ]
