# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180218_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='category',
        ),
    ]
