# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180218_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt_vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
