# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_alt_vegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'food'), ('beverage', 'beverage')], max_length=256),
        ),
    ]
