# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20180221_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('meal', 'Meal'), ('snack', 'Snack'), ('alcoholic', 'Alcoholic'), ('non-alcoholic', 'Non-Alcoholic')], default='---', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('beverage', 'Beverage')], max_length=256),
        ),
    ]
