# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-22 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20180222_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='alt_vegetarian',
            new_name='alt_v',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='gluten_free',
            new_name='gf',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='vegetarian',
            new_name='v',
        ),
    ]
