# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-22 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20180222_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='course',
            field=models.CharField(default='', max_length=120),
        ),
    ]
