# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-22 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='alcohol_type',
            field=models.CharField(choices=[('beer', 'Beer'), ('wine_cider', 'Wine/Cider'), ('hard_alcohol', 'Hard Alcohol')], default='', max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='beverage_type',
            field=models.CharField(choices=[('alcohol', 'Alcohol'), ('non_alcohol', 'Non-Alcohol')], default='', max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='diet',
            field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('gluten_free', 'Gluten Free')], default='', max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='serving_type',
            field=models.CharField(choices=[('cup', 'Cup'), ('can_bottle', 'Can/Bottle')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='course',
            field=models.CharField(choices=[('food', 'Food'), ('beverage', 'Beverage')], default='', max_length=256),
        ),
    ]
