# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20180226_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('beverage_type', models.CharField(choices=[('alcohol', 'Alcohol'), ('non_alcohol', 'Non-Alcohol')], default='', max_length=256)),
                ('alcohol_type', models.CharField(choices=[('beer', 'Beer'), ('wine_cider', 'Wine/Cider'), ('hard_alcohol', 'Hard Alcohol')], default='', max_length=256)),
                ('serving_type', models.CharField(choices=[('cup', 'Cup'), ('can_bottle', 'Can/Bottle')], default='', max_length=256)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('course', models.CharField(choices=[('appetizer', 'Appetizer'), ('entree', 'Entree'), ('dessert', 'Dessert')], default='', max_length=256)),
                ('diet', models.CharField(choices=[('none', '------'), ('vegetarian', 'Vegetarian'), ('gluten_free', 'Gluten Free')], default='', max_length=256)),
                ('gf', models.BooleanField(default=False)),
                ('v', models.BooleanField(default=False)),
                ('alt_v', models.BooleanField(default=False)),
            ],
            bases=('products.product',),
        ),
    ]
