# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20180226_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='diet',
        ),
    ]
