# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_food_diet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_diet', models.CharField(choices=[('gf', 'gf'), ('v', 'v')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='new_diet',
            field=models.ManyToManyField(to='products.Diet'),
        ),
    ]
