# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 04:06
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20180226_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='best_diet',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('gf', 'gf'), ('v', 'v')], default='gf', max_length=4),
            preserve_default=False,
        ),
    ]
