# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_food_best_diet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='new_diet',
        ),
        migrations.DeleteModel(
            name='Diet',
        ),
    ]
