# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 04:11
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20180226_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='best_diet',
        ),
        migrations.AddField(
            model_name='food',
            name='dietary_restrictions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('v', 'Vegetarian'), ('vo', 'Vegetarian Option'), ('gf', 'Gluten-Free'), ('gfo', 'Gluten-Free Option')], default='', max_length=11),
            preserve_default=False,
        ),
    ]
