# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20180226_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='gluten_free',
        ),
        migrations.RemoveField(
            model_name='food',
            name='gluten_free_optional',
        ),
        migrations.RemoveField(
            model_name='food',
            name='vegetarian',
        ),
        migrations.RemoveField(
            model_name='food',
            name='vegetarian_optional',
        ),
    ]
