# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 21:51
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20180226_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='dietary_restrictions',
        ),
        migrations.AddField(
            model_name='food',
            name='diet',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('vegetarian', 'Vegetarian'), ('vegetarian_option', 'Vegetarian Option'), ('gluten_free', 'Gluten-Free'), ('gluten_free_option', 'Gluten-Free Option')], default='vegetarian', max_length=59),
            preserve_default=False,
        ),
    ]
