# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='beer_style',
            field=models.CharField(blank=True, choices=[('amber', 'Amber'), ('pale', 'Pale'), ('blonde', 'Blonde'), ('brown', 'Brown'), ('ipa', 'IPA'), ('red', 'Red'), ('wheat', 'Wheat'), ('pilsner', 'Pilsner')], max_length=256),
        ),
        migrations.AddField(
            model_name='beverage',
            name='beer_type',
            field=models.CharField(blank=True, choices=[('ale', 'Ale'), ('lager', 'Lager'), ('malt', 'Malt'), ('stout_porter', 'Stouts & Porters')], max_length=256),
        ),
        migrations.AddField(
            model_name='beverage',
            name='brewery_type',
            field=models.CharField(blank=True, choices=[('domestic', 'Domestic'), ('import', 'Import'), ('micro', 'Micro'), ('craft', 'Craft')], max_length=256),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='serving_type',
            field=models.CharField(blank=True, choices=[('cup', 'Cup'), ('can_bottle', 'Can/Bottle')], max_length=256),
        ),
        migrations.AlterField(
            model_name='food',
            name='diet',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('vegetarian_option', 'Vegetarian Option'), ('gluten_free', 'Gluten-Free'), ('gluten_free_option', 'Gluten-Free Option')], max_length=59),
        ),
    ]
