# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-02 01:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20180227_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='serving_size',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='abv',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='beer_style',
            field=models.CharField(blank=True, choices=[('amber', 'Amber'), ('pale', 'Pale'), ('blonde', 'Blonde'), ('brown', 'Brown'), ('ipa', 'IPA'), ('red', 'Red'), ('wheat', 'Wheat'), ('pilsner', 'Pilsner'), ('stout', 'Stout'), ('pilsner', 'Pilsner')], max_length=256),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='beer_type',
            field=models.CharField(blank=True, choices=[('ale', 'Ale'), ('lager', 'Lager'), ('malt', 'Malt')], max_length=256),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='ibu',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
