# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-02 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20180302_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='wine_type',
            field=models.CharField(choices=[('white', 'White'), ('red', 'Red'), ('sparkling', 'Sparkling')], default='red', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beverage',
            name='serving_type',
            field=models.CharField(choices=[('cup', 'Cup'), ('can_bottle', 'Can/Bottle')], max_length=256),
        ),
    ]
