# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20180305_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='category',
            field=models.CharField(default='beverage', max_length=256),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default='food', max_length=256),
        ),
    ]
