# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-07 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20180306_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='wine_category',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('red', 'Red'), ('sparkling', 'Sparkling')], max_length=256),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='wine_type',
            field=models.CharField(blank=True, choices=[('chardonnay', 'Chardonnay'), ('sauvignon_blanc', 'Sauvignon Blanc'), ('pinot_grigio', 'pinot_grigio'), ('riesling', 'Riesling'), ('merlot', 'Merlot'), ('red_blend', 'Red Blend'), ('white_blend', 'White Blend'), ('zinfandel', 'Zinfandel'), ('pinot_noir', 'Pinot Noir'), ('syrah', 'Syrah'), ('cabernet_sauvignon', 'Cabernet Sauvignon')], max_length=256),
        ),
    ]
