# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-12 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20180307_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='category',
            field=models.CharField(default='Beverage', max_length=256),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='wine_type',
            field=models.CharField(blank=True, choices=[('chardonnay', 'Chardonnay'), ('sauvignon_blanc', 'Sauvignon Blanc'), ('pinot_grigio', 'Pinot Grigio'), ('riesling', 'Riesling'), ('merlot', 'Merlot'), ('red_blend', 'Red Blend'), ('white_blend', 'White Blend'), ('zinfandel', 'Zinfandel'), ('pinot_noir', 'Pinot Noir'), ('syrah', 'Syrah'), ('cabernet_sauvignon', 'Cabernet Sauvignon')], max_length=256),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(default='Food', max_length=256),
        ),
    ]
