# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-18 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20180312_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stand',
            field=models.CharField(default='Food', max_length=256),
        ),
    ]
