# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-20 21:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_product_stand'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='food_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='course',
            field=models.CharField(choices=[('appetizer', 'Snack/Appetizer'), ('entree', 'Entree'), ('dessert', 'Dessert')], default='', max_length=256),
        ),
    ]
