# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-20 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20180320_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='vegetarian',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
