# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-22 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_auto_20180321_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='gluten_free',
            field=models.CharField(choices=[('appetizer', 'Snack/Appetizer'), ('entree', 'Entree'), ('dessert', 'Dessert')], default='', max_length=256),
        ),
        migrations.AddField(
            model_name='food',
            name='vegetarian',
            field=models.CharField(choices=[('appetizer', 'Snack/Appetizer'), ('entree', 'Entree'), ('dessert', 'Dessert')], default='', max_length=256),
        ),
    ]
